name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    tests:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
     
          - name: Setup PHP with pcov
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.2'
              coverage: pcov
     
          - name: Run composer install
            run: composer install -n --prefer-dist
     
          - name: Prepare Laravel Application
            run: |
              cp .env.ci .env
              php artisan key:generate
     
          - name: Run tests with phpunit/phpunit
            run: vendor/bin/phpunit --coverage-clover=coverage.xml
